baseURL = "https://stolpersteine-gangelt.de/"
languageCode = "de-DE"
title = "Stolpersteine Gangelt"
theme = "stolpersteine"
disableKinds = ["RSS", "taxonomy", "taxonomyTerm", "familie"]
[taxonomies]
  category = "categories"
  tag = "tags"
  familie = "familie"
  verlegestelle = "verlegestelle"
