hugo new menschen/emil_falkenstein
hugo new menschen/hermann_falkenstein
hugo new menschen/jeanette_falkenstein
hugo new menschen/meta_falkenstein-marx
hugo new menschen/minna_falkenstein-sassen
hugo new menschen/julia_falkenstein-zeligmann
hugo new menschen/emil_hartog
hugo new menschen/ernst_hartog
hugo new menschen/paula_hartog
hugo new menschen/berni_hertz
hugo new menschen/dieter_hertz
hugo new menschen/elise_hertz
hugo new menschen/hedwig_hertz
hugo new menschen/hermann_hertz
hugo new menschen/karel_hertz
hugo new menschen/leo_hertz
hugo new menschen/margarete_hertz
hugo new menschen/pauline_hertz
hugo new menschen/sara_hertz
hugo new menschen/albert_josephs
hugo new menschen/erna_josephs
hugo new menschen/frieda_josephs
hugo new menschen/hugo_josephs
hugo new menschen/karl_josephs
hugo new menschen/erich_leopold
hugo new menschen/hugo_leopold
hugo new menschen/ida_leopold
hugo new menschen/lion_leopold
hugo new menschen/frieda_leopold-jülich
hugo new menschen/else_leopold-wolff
hugo new menschen/isaak_lichtenstein
hugo new menschen/regina_lichtenstein
hugo new menschen/therese_memler
hugo new menschen/fritz_morgenstern
hugo new menschen/heinrich_morgenstern
hugo new menschen/irma_morgenstern-cohen
hugo new menschen/erich_rosendahl
hugo new menschen/helmut_david_rosendahl
hugo new menschen/julie_rosendahl
hugo new menschen/max_rosendahl
hugo new menschen/hilde_rosendahl-illfelder
hugo new menschen/meta_rosendahl-voss